"""Initial migration. Client and Client_address models2

Revision ID: 6d64868d1fcd
Revises: 
Create Date: 2024-06-08 18:36:53.004336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d64868d1fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_model',
    sa.Column('client_uid', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=60), nullable=False),
    sa.Column('client_last_name', sa.String(length=60), nullable=False),
    sa.Column('client_email', sa.String(length=50), nullable=False),
    sa.Column('client_user', sa.String(length=30), nullable=True),
    sa.Column('client_pass', sa.String(), nullable=False),
    sa.Column('client_created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_state', sa.String(), nullable=False),
    sa.Column('client_city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('client_uid'),
    sa.UniqueConstraint('client_email'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('client_last_name'),
    sa.UniqueConstraint('client_user')
    )
    op.create_table('client_adress_model',
    sa.Column('adress_uid', sa.String(), nullable=False),
    sa.Column('address_client_id', sa.String(), nullable=False),
    sa.Column('client_state', sa.String(), nullable=False),
    sa.Column('client_city', sa.String(), nullable=False),
    sa.Column('client_delivery_address', sa.String(), nullable=False),
    sa.Column('client_postal_code', sa.String(), nullable=False),
    sa.Column('client_created_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_client_id'], ['client_model.client_uid'], ),
    sa.PrimaryKeyConstraint('adress_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_adress_model')
    op.drop_table('client_model')
    # ### end Alembic commands ###
