"""modifying and adding role models

Revision ID: 88e7240f3179
Revises: 6d64868d1fcd
Create Date: 2024-06-09 14:48:42.700673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e7240f3179'
down_revision = '6d64868d1fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_model', schema=None) as batch_op:
        batch_op.drop_constraint('client_model_client_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('client_model_client_last_name_key', ['client_last_name'])

    # ### end Alembic commands ###
