"""modifying and adding role models

Revision ID: 9635cdfd3e0f
Revises: 88e7240f3179
Create Date: 2024-06-09 15:43:09.849766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9635cdfd3e0f'
down_revision = '88e7240f3179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_model',
    sa.Column('roles_uid', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('roles_uid'),
    sa.UniqueConstraint('role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_model')
    # ### end Alembic commands ###
